import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable}  antialiased`}>
        <main className="grid grid-cols-10 grid-rows-5  h-screen font-urbanist pr-4">
          <div className="col-span-2 row-span-5">
            <Sidebar />
          </div>
          <div className="col-span-8 col-start-3">
            <Navbar />
          </div>

          <div className="col-span-8 row-span-4 col-start-3 row-start-2">{children}</div>
        </main>
      </body>
    </html>
  );
}
